# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20151221_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='images'),
        ),
    ]
