# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(upload_to='videos'),
        ),
    ]
