# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160129_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Image'),
        ),
    ]
